resolver: lts-13.10

flags: {}

packages:
- '.'

extra-deps:
- haskus-utils-variant-2.5
- haskus-utils-1.4
- haskus-utils-data-1.1.1
- haskus-utils-types-1.3.1
- haskus-binary-1.2
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
- git: https://github.com/haskus/haskus-system.git
  commit: bfbe40915309806fa062d7af43fc1734c69d8bff
  subdirs:
      - haskus-system

ghc-options:
   "haskus-system": -fobject-code
   "$locals": -fhide-source-paths
